In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
from logistic_regression import LogisticRegression, LogisticRegressionOvR
from sklearn.model_selection import train_test_split
from preprocess import Preprocess

Loading data

In [3]:
raw_train_data = "../data/train.csv"
raw_test_data = "../data/test.csv"

Preprocessing

In [51]:
preproc = Preprocess()
raw_data = preproc.load_data(raw_train_data)
train_df, train_data = preproc.preprocess_data(raw_data)
train_data.shape

(44760, 20)

In [24]:
train_df.Label.value_counts(normalize=True)

0    0.785947
2    0.173280
1    0.040773
Name: Label, dtype: float64

In [27]:
X_train, y_train, X_valid, y_valid = preproc.train_valid_split(
    train_data, test_size=0.33, random_state=42)

In [28]:
# Creating model instance
lr = LogisticRegressionOvR(lambda_reg=0.1)

# Fitting model
lr.fit(X=X_train, y=y_train)

# Predict
y_pred = lr.predict(X=X_valid)

/Users/rafaelapinter/Library/Mobile Documents/com~apple~CloudDocs/1.UdeM/github-projects/extreme-weather-events-ift6380/notebooks/logistic_regression.py:106: RuntimeWarning: overflow encountered in exp
  def fit(self, X, y):


In [33]:
lr.get_metrics(y_true=y_valid, y_pred=y_pred)

Confusion Matrix:
[[    0     0 11629]
 [    0     0   578]
 [    0     0  2564]] 

Accuracy:
0.1736 

Precision:
0.0579 

Recall:
0.3333


tá uma porcaria

## Adding regularization

In [36]:
# Creating model instance
lr = LogisticRegressionOvR(lambda_reg=0.1)

# Fitting model
lr.fit(X=X_train, y=y_train)

# Predict
y_pred = lr.predict(X=X_valid)

# Print results
lr.get_metrics(y_true=y_valid, y_pred=y_pred)

Confusion Matrix:
[[    0     0 11629]
 [    0     0   578]
 [    0     0  2564]] 

Accuracy:
0.1736 

Precision:
0.0579 

Recall:
0.3333


ainda tá uma bela duma bosta

## Normalizando dados

In [38]:
X_train = preproc.normalize_data(X_train)
X_valid = preproc.normalize_data(X_valid)

In [43]:
# Creating model instance
lr = LogisticRegressionOvR(learning_rate=0.02, num_iterations=1000, lambda_reg=0.1)

# Fitting model
lr.fit(X=X_train, y=y_train)

# Predict
y_pred = lr.predict(X=X_valid)

# Print results
lr.get_metrics(y_true=y_valid, y_pred=y_pred)

Confusion Matrix:
[[    0     0 11629]
 [    0     0   578]
 [    0     0  2564]] 

Accuracy:
0.1736 

Precision:
0.0579 

Recall:
0.3333


## Alterando regularização

In [45]:
# Creating model instance
lr = LogisticRegressionOvR(learning_rate=0.02, num_iterations=1000, lambda_reg=0.5)

# Fitting model
lr.fit(X=X_train, y=y_train)

# Predict
y_pred = lr.predict(X=X_valid)

# Print results
lr.get_metrics(y_true=y_valid, y_pred=y_pred)

/Users/rafaelapinter/Library/Mobile Documents/com~apple~CloudDocs/1.UdeM/github-projects/extreme-weather-events-ift6380/notebooks/logistic_regression.py:125: RuntimeWarning: overflow encountered in exp
  # Update weights


Confusion Matrix:
[[11629     0     0]
 [  578     0     0]
 [ 2564     0     0]] 

Accuracy:
0.7873 

Precision:
0.2624 

Recall:
0.3333


## Tentando menos colunas

In [52]:
cols = ["lat", "lon", "PS", "Z1000"]

In [62]:
raw_data_sel = raw_data[cols]

train_df, train_data = preproc.preprocess_data(raw_data)

In [133]:
X_train, y_train, X_valid, y_valid = preproc.train_valid_split(
    train_data, test_size=0.33, random_state=42)

In [134]:
X_train = preproc.normalize_data(X_train)
X_valid = preproc.normalize_data(X_valid)

In [ ]:
# Creating model instance
lr = LogisticRegressionOvR(learning_rate=0.01, num_iterations=200, lambda_reg=0.1)

# Fitting model
lr.fit(X=X_train, y=y_train)

# Predict
y_pred = lr.predict(X=X_valid)

# Print results
lr.get_metrics(y_true=y_valid, y_pred=y_pred)

## Tentando um modelo só

In [87]:
X_train, y_train, X_valid, y_valid = preproc.train_valid_split(
    train_data, test_size=0.33, random_state=42)

In [117]:
X_train = preproc.normalize_data(X_train)
X_valid = preproc.normalize_data(X_valid)

In [122]:
# Creating model instance
lr = LogisticRegression(learning_rate=0.1, num_iterations=100, lambda_reg=0.1)

# Fitting model
lr.fit(X=X_train, y=y_train)

# Predict
y_pred = lr.predict(X=X_valid, augment=True)

# Print results
lr.get_metrics(y_true=y_valid, y_pred=y_pred)

Confusion Matrix:
[[    0  2564]
 [    0 12207]] 

Accuracy:
0.8264 

Precision:
0.4132 

Recall:
0.5


## Tentando undersample

In [136]:
train_0 = train_df[train_df['Label'] == 0].sample(n=7756)
train_2 = train_df[train_df['Label'] == 2].copy()

train_set_balaced = pd.concat([train_0, train_2])

In [137]:
train_set_balaced = train_set_balaced.to_numpy()

In [143]:
X_train = preproc.normalize_data(X_train)
X_valid = preproc.normalize_data(X_valid)

In [144]:
X_train, y_train, X_valid, y_valid = preproc.train_valid_split(
    train_set_balaced, test_size=0.33, random_state=42)

In [145]:
# Creating model instance
lr = LogisticRegression(learning_rate=0.01, num_iterations=200, lambda_reg=0.1)

# Fitting model
lr.fit(X=X_train, y=y_train)

# Predict
y_pred = lr.predict(X=X_valid, augment=True)

# Print results
lr.get_metrics(y_true=y_valid, y_pred=y_pred)

Confusion Matrix:
[[   0 2560    0]
 [   0    0    0]
 [   0 2559    0]] 

Accuracy:
0.0 

Precision:
0.0 

Recall:
0.0


## Dropando mais colunas