In [1]:
%load_ext autoreload
%autoreload 2

In [13]:
import pandas as pd
import numpy as np
from logistic_medium import LogisticMedium
from sklearn.model_selection import train_test_split
from preprocess import Preprocess

Loading data

In [3]:
raw_train_data = "../data/train.csv"
raw_test_data = "../data/test.csv"

Preprocessing

In [4]:
preproc = Preprocess()
raw_data = preproc.load_data(raw_train_data)
train_df, train_data = preproc.preprocess_data(raw_data)
train_data.shape

(44760, 20)

In [5]:
train_df.Label.value_counts(normalize=True)

0    0.785947
2    0.173280
1    0.040773
Name: Label, dtype: float64

In [6]:
X_train, y_train, X_valid, y_valid = preproc.train_valid_split(
    train_data, test_size=0.33, random_state=42)

In [38]:
X_train = preproc.normalize_data(X_train)
X_valid = preproc.normalize_data(X_valid)

Teste com uma classe só

In [14]:
y_train = (y_train == 1).astype(int)
y_valid = (y_valid == 1).astype(int)

In [16]:
y_valid

array([0, 0, 0, ..., 0, 0, 0])

In [15]:
# Creating model instance
lr = LogisticMedium()

# Fitting model
lr.train_model(X_train, y_train, X_valid, y_valid)

# Predict
y_pred = lr.predict(X=X_valid)

ValueError: operands could not be broadcast together with shapes (29989,) (1,19) 

In [33]:
lr.get_metrics(y_true=y_valid, y_pred=y_pred)

Confusion Matrix:
[[    0     0 11629]
 [    0     0   578]
 [    0     0  2564]] 

Accuracy:
0.1736 

Precision:
0.0579 

Recall:
0.3333
